import { Sidebar } from "@/components/layout/sidebar";
import "./globals.css";
import { HiX } from "react-icons/hi";
import { AiOutlineBranches } from "react-icons/ai";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en" className="dark">
      <body className="flex flex-col w-full h-screen overflow-hidden justify-center items-center">
        <div className="flex flex-col w-full h-full overflow-auto ">
          <div className="rounded-lg bg-gray-900 w-full flex-1">
            {children}
          </div>
        </div>
        <Sidebar />
      </body>
    </html>
  );
}
